WITH
  EXPENSIVE AS (
    SELECT
      CATEGORY,
      MAX(PRICE) AS MAX_PRICE
    FROM
      FOOD_PRODUCT
    WHERE
      CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY
      CATEGORY
  )
SELECT
  EXPENSIVE.CATEGORY,
  MAX_PRICE,
  PRODUCT_NAME
FROM
  FOOD_PRODUCT
  JOIN EXPENSIVE ON EXPENSIVE.CATEGORY = FOOD_PRODUCT.CATEGORY
  AND EXPENSIVE.MAX_PRICE = FOOD_PRODUCT.PRICE
ORDER BY
  MAX_PRICE DESC