SELECT
    ANIMAL_ID,
    ANIMAL_INS.ANIMAL_TYPE,
    ANIMAL_INS.NAME
FROM
    ANIMAL_INS
    JOIN ANIMAL_OUTS USING (ANIMAL_ID)
WHERE
    SEX_UPON_INTAKE LIKE 'Intact%'
    AND SEX_UPON_OUTCOME NOT LIKE 'Intact%'
ORDER BY
    ANIMAL_ID