WITH
  MOST_MEMBER AS (
    SELECT
      MEMBER_ID,
      MEMBER_NAME
    FROM
      REST_REVIEW
      JOIN MEMBER_PROFILE USING (MEMBER_ID)
    GROUP BY
      MEMBER_ID
    ORDER BY
      COUNT(*) DESC
    LIMIT
      1
  )
SELECT
  MEMBER_NAME,
  REVIEW_TEXT,
  DATE_FORMAT (REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
  REST_REVIEW
  JOIN MOST_MEMBER USING (MEMBER_ID)
ORDER BY
  REVIEW_DATE,
  REVIEW_TEXT