WITH
  MAX_SIZE_YEAR AS (
    SELECT
      YEAR (DIFFERENTIATION_DATE) AS YEAR,
      MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM
      ECOLI_DATA
    GROUP BY
      YEAR
  )
SELECT
  YEAR (DIFFERENTIATION_DATE) AS YEAR,
  (
    SELECT
      MAX_SIZE
    FROM
      MAX_SIZE_YEAR
    WHERE
      YEAR = YEAR (DIFFERENTIATION_DATE)
  ) - SIZE_OF_COLONY AS YEAR_DEV,
  ID
FROM
  ECOLI_DATA
ORDER BY
  YEAR,
  YEAR_DEV